version: "3.9"

# Carregar variáveis do arquivo .env
# Certifique-se de ter o arquivo .env no diretório do projeto

services:
  docmost:
    image: docmost/docmost:latest
    restart: unless-stopped
    depends_on:
      - redis
    environment:
      # URL pública
      APP_URL: "${APP_URL}"
      # Gere um segredo forte
      APP_SECRET: "${APP_SECRET}"

      # Postgres próprio
      DATABASE_URL: "${DATABASE_URL}"

      # Redis local deste compose
      REDIS_URL: "redis://redis:6379"

      # Armazenamento em MinIO (S3 compatible)
      STORAGE_DRIVER: "${STORAGE_DRIVER}"
      AWS_S3_ACCESS_KEY_ID: "${AWS_S3_ACCESS_KEY_ID}"
      AWS_S3_SECRET_ACCESS_KEY: "${AWS_S3_SECRET_ACCESS_KEY}"
      AWS_S3_REGION: "${AWS_S3_REGION}"
      AWS_S3_BUCKET: "${AWS_S3_BUCKET}"
      AWS_S3_ENDPOINT: "${AWS_S3_ENDPOINT}"
      AWS_S3_FORCE_PATH_STYLE: "${AWS_S3_FORCE_PATH_STYLE}"
      # Opcional: limite de upload
      FILE_UPLOAD_SIZE_LIMIT: "${FILE_UPLOAD_SIZE_LIMIT}"

      # SMTP (ajuste para o seu provedor, indispensável para convites/reset de senha)
      MAIL_DRIVER: "${MAIL_DRIVER}"
      SMTP_HOST: "${SMTP_HOST}"
      SMTP_PORT: "${SMTP_PORT}"
      SMTP_USERNAME: "${SMTP_USERNAME}"
      SMTP_PASSWORD: "${SMTP_PASSWORD}"
      SMTP_SECURE: "${SMTP_SECURE}"
      MAIL_FROM_ADDRESS: "${MAIL_FROM_ADDRESS}"
      MAIL_FROM_NAME: "${MAIL_FROM_NAME}"

    volumes:
      - uploads_data:/app/uploads
    networks:
      - gwan
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=gwan"
      - "traefik.http.routers.docmost.rule=Host(`docs.gwan.com.br`)"
      - "traefik.http.routers.docmost.entrypoints=websecure"
      - "traefik.http.routers.docmost.tls.certresolver=letsencrypt"
      - "traefik.http.services.docmost.loadbalancer.server.port=3000"

  redis:
    image: redis:7.2-alpine
    restart: unless-stopped
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    volumes:
      - redis_data:/data
    networks:
      - gwan

volumes:
  redis_data:
    driver: local
  uploads_data:
    driver: local
