version: "3.9"

networks:
  gwan:
    external: true

services:
  docmost:
    image: docmost/docmost:latest
    restart: unless-stopped
    depends_on:
      - redis
    environment:
      # URL pública
      APP_URL: "https://docs.gwan.com.br"
      # Gere um segredo forte
      APP_SECRET: "pazdedeus@2025_gwan_docmost_secret_key_for_production_use_this_string_minimum_32_characters_long"

      # Postgres próprio
      DATABASE_URL: "postgresql://postgres:pazdedeus@postgres.gwan.com.br:5433/gwan?schema=public"

      # Redis local deste compose
      REDIS_URL: "redis://redis:6379"

      # Armazenamento em MinIO (S3 compatible)
      STORAGE_DRIVER: "s3"
      AWS_S3_ACCESS_KEY_ID: "admin"
      AWS_S3_SECRET_ACCESS_KEY: "pazdeDeus@2025"
      AWS_S3_REGION: "us-east-1"        # qualquer valor; MinIO ignora região
      AWS_S3_BUCKET: "docmost"          # crie esse bucket no MinIO
      AWS_S3_ENDPOINT: "http://minio.gwan.com.br"
      AWS_S3_FORCE_PATH_STYLE: "true"
      # Opcional: limite de upload
      FILE_UPLOAD_SIZE_LIMIT: "50mb"

      # SMTP (ajuste para o seu provedor, indispensável para convites/reset de senha)
      MAIL_DRIVER: "smtp"
      SMTP_HOST: "smtp.hostinger.com"
      SMTP_PORT: "465"
      SMTP_USERNAME: "pedro.almeida@gwan.com.br"
      SMTP_PASSWORD: "pazdedeus@2025"
      SMTP_SECURE: "true"
      MAIL_FROM_ADDRESS: "pedro.almeida@gwan.com.br"
      MAIL_FROM_NAME: "Docmost - Gwan"

    networks:
      - gwan
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=gwan"
      - "traefik.http.routers.docmost.rule=Host(`docs.gwan.com.br`)"
      - "traefik.http.routers.docmost.entrypoints=websecure"
      - "traefik.http.routers.docmost.tls.certresolver=letsencrypt"
      - "traefik.http.services.docmost.loadbalancer.server.port=3000"

  redis:
    image: redis:7.2-alpine
    restart: unless-stopped
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    volumes:
      - redis_data:/data
    networks:
      - gwan

volumes:
  redis_data:
    driver: local
